### ISSUE TITLE
Weight vs hash

### ISSUE THREAD

**Issue by rohitjoshi** [openresty/lua-resty-balancer#1]
How can I choose servers based on the weight and not the hash?

**Comment by doujiang24** [comment]
@rohitjoshi Sorry, I'm not really understand what your mean.
Could you show me an example?

**Comment by rohitjoshi** [comment]
Now I understand. closing...

**Comment by rohitjoshi** [comment]
@doujiang24 resty-cash module load balances based on the hash.  I want to load balance using round robin. How can I achieve this?
@agentzh

**Comment by agentzh** [comment]
@doujiang24 says he will look into it these days.

**Comment by agentzh** [comment]
@rohitjoshi Round-robin is much much simpler than consistent hashing in algorithm.

**Comment by rohitjoshi** [comment]
@agentzh thanks. I thought with RB, we need to keep track of previously used connection index essentially maintaining a state for each upstream and updating it versus hashing is more a lookup once initialized.

**Comment by doujiang24** [comment]
@rohitjoshi I just finished `resty.roundrobin,` the apis are keeped as same as `resty.chash`.
There is a simple usage in the test case `t/roundrobin.t`
Any feedbacks are welcome :)

**Comment by rohitjoshi** [comment]
@doujiang24 thanks.  I will try this out tomorrow.

**Comment by rohitjoshi** [comment]
@doujiang24 works great. Thanks
@agentzh it would be good to include both of these modules as part of balancer_by_lua where provided upstream data, it automatically takes care of that similar to nginx upstream file.

**Comment by agentzh** [comment]
@rohitjoshi Yeah, that has been the plan :)
