### ISSUE TITLE
make: unrecognized command line option "-flto"

### ISSUE THREAD

**Issue by xiaoxuanzi** [openresty/lua-resty-balancer#10]
I found a error:

[root@]# make
cc -Wall -O3 -flto -g -DFP_RELAX=0 -DDEBUG -fPIC -MMD -fvisibility=hidden -DBUILDING_SO -c chash.c
cc1: error: unrecognized command line option "-flto"
make: *** [chash.o] error 1

AND

#gcc -v:
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)

## I delete "-flto"  AND it work  correctly.

"-flto"  support after GCC 4.7

**Comment by doujiang24** [comment]
Yeah, you need a higher version gcc :)
