### ISSUE TITLE
Any plan to share the state of load balancing across workers?

### ISSUE THREAD

**Issue by ElvinEfendi** [openresty/lua-resty-balancer#23]
I might be mistaken but looking at the implementation seems like the state of a load balancing algorithm is per Nginx worker. This means if for example there are 4 requests hitting 4 different workers then they will all be proxied to the first upstream server.

If that is not the case then could you give some hints how the state is shared?

Thanks!

**Comment by Tieske** [comment]
removed: commented on the wrong repo. Sorry for the noise.

**Comment by ElvinEfendi** [comment]
I've realized that neither Round Robin nor Consistent Hashing requires a shared state.
