### ISSUE TITLE
can't load librestychash.so  ,how to solve

### ISSUE THREAD

**Issue by autopost-get** [openresty/lua-resty-balancer#28]
chash.lua:82: can not load librestychash.so
stack traceback:
	[C]: in function 'error'
	.../chash.lua:82: in main chunk
	[C]: in function 'require'
	...controller.lua:11: in main chunk
	[C]: in function 'require'
	init_by_lua:1: in main chunk

**Comment by rainingmaster** [comment]
@autopost-get 
Hi, it seems that you doesn't compile the `librestychash.so`, have you follow the [installation](https://github.com/openresty/lua-resty-balancer#installation) to generate `librestychash.so`, and set the right `cpath`?

**Comment by cscfamily001** [comment]
where is librestychash.so source code

**Comment by rainingmaster** [comment]
> where is librestychash.so source code




https://github.com/openresty/lua-resty-balancer/blob/master/chash.c
