### ISSUE TITLE
How to use the resty.chash

### ISSUE THREAD

**Issue by tjliupeng** [openresty/lua-resty-balancer#4]
@doujiang24 ,

With your example code in Synopsis, I have no idea how to use the resty.chash. What usage of the weight? How does the weight relate to the hash for session sticky? You mentioned that we can balance by any key when using chash_up:find(ngx.var.arg_key). When we initialize chash_up(), do we need this key? Is it possible to find by session id?

Would you like to describe it in more detail?

Thanks

**Comment by prehawk1999** [comment]
I think looking at testcase at t/ is the best way to learn how to use :)
And for the first question. For example, {server1 = 1, server2 = 2}, then requests forward to server2 will be close to twice than that forward to server1.

For the second question, key that used by find have nothing to do with the initialization. 
For example, when you find servers by an auto increment id str, like "foo1", "foo2", ... , "foon", server balance will be close to your config.

**Comment by tjliupeng** [comment]
@prehawk1999, seems resty.chash has no relevance to session sticky, right?

**Comment by doujiang24** [comment]
@tjliupeng 
Does session sticky means: same session always go to the same server?
`local id = chash:find(session_key)`
Yes, same `session_key` always get the same `id` :)

**Comment by tjliupeng** [comment]
@doujiang24 , below is my policy, how to implement that:
For the first request, it has no cookie JSESSIONID, then I need to assign an upstream server to this request, I use`id = chash:find()`; for the later request in the same session, it has cookie JSESSIONID, I still need to assign the same upstream server to it, I use `id = chash:find(JSESSIONID)`. How to achieve that? My current code below does not work:

```
balancer_by_lua_block {
            local b = package.loaded.balancer
            local chash_up = package.loaded.my_chash_up
            local servers = package.loaded.my_servers
            local cookie_name = "JSESSIONID"
            local var_name = "cookie_" .. cookie_name
            local cookie_value = ngx.var[var_name]
            if (cookie_value ~= nil) then
                local id = chash_up:find(cookie_value)
                ngx.log(ngx.ERR, " id for JSESSIONID ", cookie_value, " is ", id)
                local server = servers[id]
                ngx.log(ngx.ERR, " The server for id ", id, " is ", server)
                assert(b.set_current_peer(server))
            else
                local id = chash_up:find()
                ngx.log(ngx.ERR, " id for first request is ", id)
                local server = servers[id]
                ngx.log(ngx.ERR, " The server for id ", id, " is ", server)
                chash_up:down(id)
                assert(b.set_current_peer(server))
            end
        }
```

Should I need to call  chash_up:down() to decrease the weight for the id then other server could be assigned for the new session?

Thanks

**Comment by doujiang24** [comment]
@tjliupeng 
Does the `JSESSIONID` from your backend server? If yes, then it seems impossible.
You'd better move `JSESSIONID` or another key to OpenResty, for example:

```
local cookie = ngx.var.cookie_your_key
if not cookie then
    cookie = gen_cookie()
    set_cookie(your_key, cookie)
end
local id = chash:find(cookie)
```

**Comment by agentzh** [comment]
@doujiang24 I think `$cookie_NAME` is always the value of the _request_ cookie.

@tjliupeng I think you should prepare a minimal and standalone example that can be easily run on our side. Also, simply saying "does not work" is not helpful at all. You should really give as many details as possible, like exactly what you are seeing from the http client side or in the nginx error log file. See below for more details on how to report a problem properly:

http://openresty.org/en/faq.html#how-should-i-report-a-problem

Thanks for your cooperation.

**Comment by tjliupeng** [comment]
@agentzh ， thanks for your comment. I try to follow it. 
Below is lua code in my nginx.conf:

```
init_by_lua_block {
     package.loaded.balancer = require "ngx.balancer"
        local upstream = require "ngx.upstream"
        local get_servers = upstream.get_servers
        local resty_chash = require "resty.chash"
        collectgarbage("collect")  -- just to collect any garbage

        function split(source, delimiters)
            local elements = {}
            local pattern = '([^'..delimiters..']+)'
            string.gsub(source, pattern, function(value) elements[#elements + 1] =     value;  end);
            return elements
        end
         up_srvs={"15.107.4.15:13080", "15.107.4.15:13081"}
         local str_null = string.char(0)
         local servers, nodes = {}, {}
         for k,v in pairs(up_srvs) do
             ngx.log(ngx.ERR, "raw server is ", v)
             local id = string.gsub(v, ":", str_null)
             ngx.log(ngx.ERR, "id is ", id)
             servers[id] = v
             nodes[id] = 4
         end
         local chash_up = resty_chash:new(nodes)
         package.loaded.my_chash_up = chash_up
         package.loaded.my_servers = servers
end
upstream sm {
        server 15.107.4.15:13080;
        server 15.107.4.15:13081;
        #sticky ;
        #limit_upstream_conn limit=5 zone=test backlog=10000 timeout=180s;
        #limit_upstream_log_level error;
        balancer_by_lua_block {
            local b = package.loaded.balancer
            local chash_up = package.loaded.my_chash_up
            local servers = package.loaded.my_servers

            local cookie_name = "JSESSIONID"
            local var_name = "cookie_" .. cookie_name
            local cookie_value = ngx.var[var_name]
            local sessionid_server = ngx.shared.sessionid_server_dict

            if (cookie_value ~= nil) then
                local server = sessionid_server:get(cookie_value)
               assert(b.set_current_peer(server))
            else
                local id = chash_up:find()
                ngx.log(ngx.ERR, " id for first request is ", id)
                local server = servers[id]
                ngx.log(ngx.ERR, " The server for id ", id, " is ", server)
                chash_up:down(id)
                assert(b.set_current_peer(server))
            end
        }
    }

```

There are 2 nodes: 15.107.4.15:13080 and 15.107.4.15:13081. In the init block, the weight of each node is assigned to 4. In balancer block, when the JSESSIONID is null, using chash_up:find() to get an id then get a server node for this new session. Then chash_up.down() is called to decrease the weight. However, when I try several new sessions, these sessions always get node 15.107.4.15:13081. Seem the down method does not take effect.

**Comment by agentzh** [comment]
@tjliupeng Why are you calling `down()`? It's not decreasing the weight, it's marking that node _down_.

**Comment by agentzh** [comment]
@tjliupeng "down" here means making the node in question _offline_.

**Comment by agentzh** [comment]
@doujiang24 Seems like we need to add more docs here to avoid such confusions ;)

https://github.com/agentzh/lua-resty-balancer#down

**Comment by tjliupeng** [comment]
@agentzh , even the semantics of "down" means this node is offline, it does not affect the result of chash_up:find(). chash_up is built based on nodes which is a table for id->weight mapping. several continuous call to chash_up:find() return the same result. My expectation is round-robin.

**Comment by agentzh** [comment]
@tjliupeng In your example, there are only 2 servers configured. After you mark one server "down", then there is only the other server standing, meaning all the sessions will map to the only remaining server. This looks completely reasonable to me, no?

**Comment by agentzh** [comment]
@tjliupeng It has nothing to do with "weight" btw, just "availability".

**Comment by agentzh** [comment]
@tjliupeng You shouldn't call `down()` in the first place. You should only mark a node offline when you know that node is problematic (like timeout or 500 or something).

**Comment by tjliupeng** [comment]
@agentzh , even I comment the line for down(), I get the same result: all the new sessions always get the node 15.107.4.15:13081. According to your comment, if the node is marked to down, then the new sesssions should get the node 15.107.4.15:1308**0**, actually get 15.107.4.15:1308**1**.

**Comment by tjliupeng** [comment]
At least from the code chash.lua, the up() and down() are related to weight operation.

**Comment by ssdr** [comment]
maybe the problem is Package.loaded.*, it seems not shared between different workers?

**Comment by doujiang24** [comment]
@agentzh Sorry for the confused api, `down` is decrease weight now :(
Maybe we can use `incr` and `decr` instead `up` and `down`?

ps: we have `add` and `delete` api :)

**Comment by doujiang24** [comment]
@tjliupeng `chash:find()` equals `chash:find("nil")`.
It means you are always use the same key to find :)
So, it's better to use a req_cookie like `JSESSIONID` to find: `chash:find(JSESSIONID)`

**Comment by doujiang24** [comment]
@agentzh I just renamed `up`/`down` to `incr`/`decr` and added more doc.
Please let me know if there is any problem.

@tjliupeng Sorry for the api changed, my fault :(
`down` is an confused api, `down` always mean offline in nginx's world.

**Comment by tjliupeng** [comment]
@doujiang24 , thanks for your update.

**Comment by Triple-Z** [comment]
@doujiang24 
> ps: we have `add` and `delete` api :)

I can't find `add` API in any version of this repo, can I use `incr` API to add a new server to chash object?
