### ISSUE TITLE
can chash object be reinitialized？

### ISSUE THREAD

**Issue by ssdr** [openresty/lua-resty-balancer#5]
say，can I call new() for many times or not?
if I call new() with nodes(a,b,c)，then one object be hashed to server b;
later I call new() with nodes(a,b)，will the same object be hashed to server b still?

**Comment by doujiang24** [comment]
@ssdr  I guess you mean `later I call new() with nodes(a,b,c) again` ?

**Comment by ssdr** [comment]
no，with nodes(a, b), c is down at that time, I call new() with nodes(a, b), will it affact hash results?

**Comment by doujiang24** [comment]
@ssdr Yes, I just add a test case for incr/decr weight:
https://github.com/agentzh/lua-resty-balancer/blob/master/t/chash.t#L209

**Comment by ssdr** [comment]
@doujiang24 that sounds pretty good~ 😜

**Comment by doujiang24** [comment]
Consider resolved
